# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_name=Sprintum
mod_id=sprintum
mod_author=Riflusso
mod_version=0.1.0
mod_description=\
  Reverts the fix for the bug [MC-152728] where players could continue sprinting \
  while performing actions that normally slow them down \
  (e.g., blocking with a shield, eating, sneaking)
license=All Rights Reserved
maven_group=net.riflusso
archives_name=sprintum
enabled_platforms=fabric,neoforge

# Minecraft properties
minecraft_version=1.21.4

#Fabric
fabric_loader_version=0.16.9
fabric_version=0.110.5+1.21.4
modmenu=13.0.0-beta.1

#NeoForge
neoforge_version=21.4.3-beta
