modLoader = "javafml"
loaderVersion = "[2,)"
license = "${license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors = "${mod_author}"
description = "${mod_description}"
logoFile = "assets/sprintum/icon.png"

[[dependencies.sprintum]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sprintum]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.4,)"
ordering = "NONE"
side = "BOTH"


[[mixins]]
config = "sprintum.mixins.json"
